name = "volt-price-aggregator"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["*/5 * * * *"]  # every 5 minutes

[[kv_namespaces]]
binding = "VOLT_PRICING"
id = "0629eef9f4824fd49a1b0fd58cc23253"
